# Generated by Django 5.1.7 on 2025-04-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_jobposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'about_me',
                'indexes': [models.Index(fields=['uid'], name='about_me_uid_fa920b_idx')],
            },
        ),
    ]
