# Generated by Django 5.1.7 on 2025-04-15 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=255)),
                ('degree', models.CharField(choices=[('High School', 'High School'), ('Bachelor', "Bachelor's"), ('Master', "Master's"), ('PhD', 'PhD'), ('Other', 'Other')], max_length=20)),
                ('field_of_study', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='api.user', to_field='uid')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'db_table': 'education',
            },
        ),
    ]
