# Generated by Django 5.1.7 on 2025-04-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobScope',
            fields=[
                ('jid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=100)),
                ('scope', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_scope',
                'indexes': [models.Index(fields=['uid'], name='job_scope_uid_46ed20_idx')],
            },
        ),
    ]
