# Generated by Django 5.1.7 on 2025-04-23 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_jobscope'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_uid', on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='api.user', to_field='uid')),
                ('user', models.ForeignKey(db_column='user_uid', on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='api.user', to_field='uid')),
            ],
            options={
                'verbose_name': 'Favourite',
                'verbose_name_plural': 'Favourites',
                'db_table': 'favourites',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
