# Generated by Django 5.2 on 2025-04-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('company', 'Company'), ('admin', 'Admin'), ('staff', 'Staff')], default='employee', max_length=10),
        ),
    ]
