# Generated by Django 5.2 on 2025-04-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
