# Generated by Django 5.2 on 2025-04-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=10)),
                ('f_title', models.CharField(max_length=255)),
                ('f_description', models.TextField()),
                ('staff_id', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('resolved', 'Resolved')], default='new', max_length=10)),
                ('reply', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'db_table': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
